 export const servicesData = {
  "website-development": {
    title: "Website Development",
    description: "Lightning-fast, SEO-optimized websites built with Next.js, React and modern technologies.",
    icon: "🌐",
    gradient: "from-blue-600 to-cyan-500",
    features: ["Custom Design", "Mobile-First Responsive", "SEO Optimized", "Fast Loading", "CMS Integration", "24/7 Security"],
    benefits: ["Increase conversions by 40%", "Reduce bounce rate by 35%", "Improve load time by 50%", "Rank higher on Google"],
    stats: [{ value: "150+", label: "Websites Built" }],
    process: ["Discovery", "Design", "Development", "Launch"],
    technologies: ["Next.js", "React", "Tailwind CSS", "Node.js"],
  },
  "ecommerce-development": {
    title: "E-Commerce Development",
    description: "Conversion-focused online stores with seamless shopping experiences.",
    icon: "🛒",
    gradient: "from-purple-600 to-pink-500",
    features: ["Payment Integration", "Product Management", "Order Tracking", "Customer Accounts", "Inventory", "Analytics"],
    benefits: ["Boost sales by 60%", "Reduce cart abandonment", "Increase retention", "Streamline operations"],
    stats: [{ value: "$10M+", label: "Revenue Generated" }],
    process: ["Research", "Design", "Setup", "Launch"],
    technologies: ["Shopify", "WooCommerce", "Stripe", "React"],
  },
  "seo": {
    title: "SEO Optimization",
    description: "Data-driven SEO strategies that boost rankings and drive organic traffic.",
    icon: "📈",
    gradient: "from-green-600 to-emerald-500",
    features: ["Keyword Research", "On-Page SEO", "Technical SEO", "Link Building", "Content Marketing", "Analytics"],
    benefits: ["Rank #1 on Google", "Increase traffic 200%", "Generate quality leads", "Build authority"],
    stats: [{ value: "10M+", label: "Keywords Ranked" }],
    process: ["Audit", "Strategy", "Implementation", "Monitoring"],
    technologies: ["Google Analytics", "SEMrush", "Ahrefs", "Yoast"],
  },
  "google-ads": {
    title: "Google Ads",
    description: "High-performing Google Ads campaigns that deliver targeted traffic and maximize ROI.",
    icon: "🎯",
    gradient: "from-red-600 to-orange-500",
    features: ["Campaign Strategy", "Keyword Bidding", "Ad Copy", "Landing Page", "Performance Tracking", "Budget Management"],
    benefits: ["Reduce CPC by 40%", "Increase conversion rate", "Target ideal customers", "Scale campaigns"],
    stats: [{ value: "$50M+", label: "Ad Spend Managed" }],
    process: ["Goal Setting", "Setup", "Testing", "Scaling"],
    technologies: ["Google Ads", "Keyword Planner", "Google Analytics"],
  },
  "meta-ads": {
    title: "Meta Ads",
    description: "Facebook & Instagram advertising that builds brand awareness and drives conversions.",
    icon: "📱",
    gradient: "from-blue-700 to-indigo-600",
    features: ["Audience Targeting", "Creative Design", "A/B Testing", "Retargeting", "Analytics", "Budget Optimization"],
    benefits: ["Reach millions", "Increase brand awareness", "Drive quality traffic", "Build engagement"],
    stats: [{ value: "100M+", label: "Impressions Generated" }],
    process: ["Research", "Creative", "Launch", "Optimization"],
    technologies: ["Meta Ads Manager", "Canva", "Facebook Pixel"],
  },
  "social-media-marketing": {
    title: "Social Media Marketing",
    description: "Strategic social media marketing that builds communities and drives business growth.",
    icon: "💬",
    gradient: "from-pink-600 to-rose-500",
    features: ["Content Strategy", "Community Management", "Influencer Marketing", "Brand Storytelling", "Analytics", "Campaign Management"],
    benefits: ["Grow followers by 200%", "Increase engagement", "Build brand loyalty", "Drive traffic"],
    stats: [{ value: "5M+", label: "Community Reach" }],
    process: ["Strategy", "Content", "Community", "Analysis"],
    technologies: ["Meta Suite", "Hootsuite", "Canva", "Buffer"],
  },
};

export type ServiceKey = keyof typeof servicesData;